/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LeaguePayoutInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLeague"
      | "hasStaked"
      | "leagueBalances"
      | "leagueFeePaid"
      | "owner"
      | "payoutWinners"
      | "stake"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "LeagueCreated"
      | "Payout"
      | "PayoutCompleted"
      | "Stake"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createLeague",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasStaked",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leagueBalances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "leagueFeePaid",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutWinners",
    values: [string, AddressLike[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLeague",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasStaked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leagueBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leagueFeePaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeagueCreatedEvent {
  export type InputTuple = [
    leagueId: string,
    userId: string,
    commissionPercentage: BigNumberish,
    creator: AddressLike,
    feePaid: BigNumberish
  ];
  export type OutputTuple = [
    leagueId: string,
    userId: string,
    commissionPercentage: bigint,
    creator: string,
    feePaid: bigint
  ];
  export interface OutputObject {
    leagueId: string;
    userId: string;
    commissionPercentage: bigint;
    creator: string;
    feePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutEvent {
  export type InputTuple = [
    leagueId: string,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [leagueId: string, winner: string, amount: bigint];
  export interface OutputObject {
    leagueId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutCompletedEvent {
  export type InputTuple = [
    leagueId: string,
    totalPayout: BigNumberish,
    commission: BigNumberish
  ];
  export type OutputTuple = [
    leagueId: string,
    totalPayout: bigint,
    commission: bigint
  ];
  export interface OutputObject {
    leagueId: string;
    totalPayout: bigint;
    commission: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    userId: string,
    leagueId: string
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    userId: string,
    leagueId: string
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    userId: string;
    leagueId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LeaguePayout extends BaseContract {
  connect(runner?: ContractRunner | null): LeaguePayout;
  waitForDeployment(): Promise<this>;

  interface: LeaguePayoutInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLeague: TypedContractMethod<
    [leagueId: string, userId: string, commissionPercentage: BigNumberish],
    [void],
    "payable"
  >;

  hasStaked: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  leagueBalances: TypedContractMethod<[arg0: string], [bigint], "view">;

  leagueFeePaid: TypedContractMethod<[arg0: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payoutWinners: TypedContractMethod<
    [
      leagueId: string,
      winners: AddressLike[],
      winningPercentages: BigNumberish[],
      commissionPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [leagueId: string, userId: string],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLeague"
  ): TypedContractMethod<
    [leagueId: string, userId: string, commissionPercentage: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "hasStaked"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "leagueBalances"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "leagueFeePaid"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutWinners"
  ): TypedContractMethod<
    [
      leagueId: string,
      winners: AddressLike[],
      winningPercentages: BigNumberish[],
      commissionPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[leagueId: string, userId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "LeagueCreated"
  ): TypedContractEvent<
    LeagueCreatedEvent.InputTuple,
    LeagueCreatedEvent.OutputTuple,
    LeagueCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Payout"
  ): TypedContractEvent<
    PayoutEvent.InputTuple,
    PayoutEvent.OutputTuple,
    PayoutEvent.OutputObject
  >;
  getEvent(
    key: "PayoutCompleted"
  ): TypedContractEvent<
    PayoutCompletedEvent.InputTuple,
    PayoutCompletedEvent.OutputTuple,
    PayoutCompletedEvent.OutputObject
  >;
  getEvent(
    key: "Stake"
  ): TypedContractEvent<
    StakeEvent.InputTuple,
    StakeEvent.OutputTuple,
    StakeEvent.OutputObject
  >;

  filters: {
    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "LeagueCreated(string,string,uint256,address,uint256)": TypedContractEvent<
      LeagueCreatedEvent.InputTuple,
      LeagueCreatedEvent.OutputTuple,
      LeagueCreatedEvent.OutputObject
    >;
    LeagueCreated: TypedContractEvent<
      LeagueCreatedEvent.InputTuple,
      LeagueCreatedEvent.OutputTuple,
      LeagueCreatedEvent.OutputObject
    >;

    "Payout(string,address,uint256)": TypedContractEvent<
      PayoutEvent.InputTuple,
      PayoutEvent.OutputTuple,
      PayoutEvent.OutputObject
    >;
    Payout: TypedContractEvent<
      PayoutEvent.InputTuple,
      PayoutEvent.OutputTuple,
      PayoutEvent.OutputObject
    >;

    "PayoutCompleted(string,uint256,uint256)": TypedContractEvent<
      PayoutCompletedEvent.InputTuple,
      PayoutCompletedEvent.OutputTuple,
      PayoutCompletedEvent.OutputObject
    >;
    PayoutCompleted: TypedContractEvent<
      PayoutCompletedEvent.InputTuple,
      PayoutCompletedEvent.OutputTuple,
      PayoutCompletedEvent.OutputObject
    >;

    "Stake(address,uint256,string,string)": TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;
    Stake: TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;
  };
}
